language: python
sudo: false

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - curl -L https://github.com/TankerHQ/dmenv/releases/download/v0.5.0/dmenv-linux -o dmenv
  - chmod u+x dmenv
  - ./dmenv install


script:
  - ./dmenv run -- python ci/ci.py
  - ./dmenv run codecov
